name: nfc_card_password_saver
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  local_auth: ^3.0.0
  lottie: ^3.3.2
  nfc_manager: ^4.1.1
  provider: ^6.1.5+1
  pull_down_button: ^0.10.2
  shared_preferences: ^2.5.4
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit/Outfit-Thin.ttf
          weight: 100
        - asset: assets/fonts/Outfit/Outfit-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Outfit/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/Outfit/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Outfit/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit/Outfit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Outfit/Outfit-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Outfit/Outfit-Black.ttf
          weight: 900
